runtime: python39
entrypoint: gunicorn -b :$PORT app:app

instance_class: F2

env_variables:
  FLASK_APP: "app.py"
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"

handlers:
  - url: /static
    static_dir: app/static

  - url: /.*
    script: auto
    secure: always

# Required for selenium/chrome
build_env_variables:
  GOOGLE_CHROME_CHANNEL: "stable"
