runtime: python39
entrypoint: gunicorn -b :$PORT app:app --timeout 120

instance_class: F4

env_variables:
  FLASK_APP: "app.py"
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"
  GAE_USE_SOCKETS_HTTPLIB: "true"

# Increase startup timeout
readiness_check:
  app_start_timeout_sec: 300

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
  - url: /static
    static_dir: app/static

  - url: /.*
    script: auto
    secure: always

# Required for selenium/chrome
build_env_variables:
  GOOGLE_CHROME_CHANNEL: "stable"
